// Autogenerated AST node
package org.python.antlr.ast;

public interface operatorType {
    public static final int Add = 1;
    public static final int Sub = 2;
    public static final int Mult = 3;
    public static final int MatMult = 4;
    public static final int Div = 5;
    public static final int Mod = 6;
    public static final int Pow = 7;
    public static final int LShift = 8;
    public static final int RShift = 9;
    public static final int BitOr = 10;
    public static final int BitXor = 11;
    public static final int BitAnd = 12;
    public static final int FloorDiv = 13;

    public static final String[] operatorTypeNames = new String[] {
        "<undef>",
        "Add",
        "Sub",
        "Mult",
        "MatMult",
        "Div",
        "Mod",
        "Pow",
        "LShift",
        "RShift",
        "BitOr",
        "BitXor",
        "BitAnd",
        "FloorDiv",
    };
}
